title: "Morteza Aliyari"
description: "UAVs, Multi-Agent Systems, Safe RL, ROS2"
theme: minima


# Optional: show post excerpts on list pages (if you later add blog posts)
show_excerpts: true

header_pages:
  - videos.md
  - projects.md
  - publications.md
  - cv.md